crypt now actually not horrible :)

diff --git a/bin/crypt b/bin/crypt
--- a/bin/crypt
+++ b/bin/crypt
@@ -1,23 +1,62 @@
-#! /bin/bash
+#! /usr/bin/env bash
 
-if [ "lol$1" = "lol" -o ! -f $1 ]
-then
-	echo "File not found:"
-	echo "    crypt <file> [-d]"
-	exit 1
+#-------------------------------------------------------------------------#
+#                                  crypt                                  #
+#                                                                         #
+# Author: Nic H.                                                          #
+# Date: 2016-Jan-29                                                       #
+#                                                                         #
+# Encrypt and decrypt files using openssl.                                #
+#                                                                         #
+# Usage:                                                                  #
+#     crypt [-c CIPHER] <file>                                            #
+# encrypts or decrypts <file> with cipher CIPHER                          #
+#-------------------------------------------------------------------------#
+
+set -u
+set -e
+
+function usage(){
+    grep "^#.*#$" $0
+}
+
+CIPHER="aes-256-cbc"
+
+while getopts "hc:" opt; do
+    case $opt in
+        h)
+            usage
+            exit 0
+            ;;
+	c)
+            CIPHER="$OPTARG"
+            ;;
+        \?)
+            exit 1
+            ;;
+    esac
+done
+shift $(($OPTIND -1))
+
+if [ $# != 1 ] || [ ! -f $1 ] ; then
+    echo "Cannot find file for encryption/decryption: $@" >&2
+    exit 1
 fi
 
-read -p "Password: " -s pass
-echo
+OUT=$1.$CIPHER.enc
+MODE=""
+MODE_NAME="encrypting"
 
-if [ "lol$2" = "lol" ]
-then
-	outname=`echo -n "$1" | openssl enc -aes-256-cbc -k $pass -a -nosalt | sed 's/=/./g' | sed 's/+/-/g' | sed 's/\//_/g'`
-	opt=
-else
-	outname=`echo "$1" | sed 's/_/\//g' | sed 's/-/+/g' | sed 's/\./=/g' | openssl enc -aes-256-cbc -k $pass -a -nosalt -d`
-	opt="-d"
+if [[ $1 =~ .*$CIPHER\.enc$ ]] ; then
+    OUT=${1%\.${CIPHER}.enc}
+    MODE="-d"
+    MODE_NAME="decrypting"
 fi
 
-echo $1 ---> $outname
-openssl enc -aes-256-cbc -k $pass -nosalt $opt -in $1 -out $outname
+if [ -f $OUT ] ; then
+    echo "Output file already exists: $OUT" >&2
+    exit 1;
+fi
+
+echo "$MODE_NAME $1 -> $OUT"
+openssl enc -$CIPHER $MODE -a -in $1 -out $OUT
